import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const chivo = Chivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <Navbar />
        <main className="px-5">{children}</main>
      </body>
    </html>
  );
}
